/*
 * This source file was generated by the Gradle 'init' task
 */
package dragonball;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;


class AppTest {

    @Test
    void testGetKiFormateado() {
        Personaje p = new Personaje(1, "Goku", "1.500.000", "Saiyan");
        assertEquals(1500000, p.getKiFormateado());
    }

    @Test
    void testGetId() {
        Personaje p = new Personaje(2, "Vegeta", "900.000", "Saiyan");
        assertEquals(2, p.getId());
    }

    @Test
    void testGetNombre() {
        Personaje p = new Personaje(3, "Piccolo", "800.000", "Namekiano");
        assertEquals("Piccolo", p.getNombre());
    }

    @Test
    void testGetKi() {
        Personaje p = new Personaje(4, "Freezer", "1.200.000", "Alien");
        assertEquals("1.200.000", p.getKi());
    }

    @Test
    void testGetRaza() {
        Personaje p = new Personaje(5, "Cell", "1.000.000", "Bio-Android");
        assertEquals("Bio-Android", p.getRaza());
    }

    @Test
    void testToString() {
        Personaje p = new Personaje(6, "Gohan", "950.000", "Saiyan");
        String esperado = "Personaje {id: 6, nombre: Gohan, ki: 950.000, raza: Saiyan}";
        assertEquals(esperado, p.toString());
    }
}
